name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: iTunesMatchTagger

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute unit tests in the solution (if a test project exists)
    - name: Execute unit tests (if any)
      run: dotnet test $env:Solution_Name.sln # Assuming your solution file is named the same
      continue-on-error: true # Don't fail the build if no tests are found

    # Restore the application
    - name: Restore the application
      run: msbuild $env:Solution_Name.sln /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the application
    - name: Build the application
      run: msbuild $env:Solution_Name.sln /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Optional: Decode the base 64 encoded pfx and save the Signing_Certificate in the root
    - name: Decode the pfx (if signing)
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path . -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Optional: Create the app package (if you have a WAP project in the solution)
    - name: Create the app package (if WAP project exists)
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      run: msbuild $env:Solution_Name.sln /t:Package /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    # Optional: Remove the pfx
    - name: Remove the pfx (if signing)
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      run: Remove-Item -path GitHubActionsWorkflow.pfx

    # Upload the build output (adjust the path as needed)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Output - ${{ matrix.configuration }}
        path: ${{ github.workspace }}/bin/${{ matrix.configuration }}/** # Adjust this path to your build output directory

    # Optional: Upload the MSIX package (if created)
    - name: Upload MSIX package (if created)
      if: ${{ secrets.Base64_Encoded_Pfx != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package - ${{ matrix.configuration }}
        path: ${{ github.workspace }}/**/AppPackages/** # Adjust this path if needed
